### ISSUE TITLE
Text wrapping on description breaks text in wrong place.

### ISSUE THREAD

**Issue by GilbertLittle** [Microsoft/powerbi-visuals-pulsechart#27]
When the text in the event description is too long to fit in the popup, the function that breaks the text, does so incorrectly and words get concatenated. The first image shows the words description and that have been joined together.
![image1-bad](https://user-images.githubusercontent.com/36719604/36564118-2b7173fc-1814-11e8-87b6-2c4dcefa5a24.PNG)
Setting the MaxWidth on the call to textMeasurementService.wordBreak (line 1744 visuals.ts in release 2.2.3) to an arbitrarily large width corrects the issue - but doesn't seem like the best fix. Image 2 shows the result of doing this (width multiplied by 500 in this case!).
![image2-good](https://user-images.githubusercontent.com/36719604/36564319-bf917212-1814-11e8-93eb-26e6c6be85c7.PNG). 
The issue persists in later releases, but 2.2.3 is the release currently available through appsource.microsoft.com.

**Comment by ignatvilesov** [comment]
Hi @GilbertLittle,

Are you still facing this issue?

**Comment by helen508light** [comment]
issue has already been resolved
