### ISSUE TITLE
Changes made since 2.2.3.0 stop the popup from automatically showing during animation

### ISSUE THREAD

**Issue by GilbertLittle** [Microsoft/powerbi-visuals-pulsechart#28]
In the current version available on appsource.microsoft (2.2.3) when you play the animation for the pulse chart, if a popup is configured, it will automatically show when the animation reaches that point. In the latest version (2.2.4) available on github, the popup does not show automatically. The difference appears to be from changes made to the handleSelection function in visual.ts.

**Comment by uve** [comment]
@GilbertLittle, to show popups when the animation reaches that point, please add any dataset to "event" or "description" values.

**Comment by GilbertLittle** [comment]
@uve ,I have done that - it works perfectly in 2.2.3, the current release version. But it doesn't work with the latest revision 2.2.4 downloaded from github. This is using the exact same dataset with the visual configured the same way. I get the issue using both power bi desktop and app.powerbi.com. Thanks.

**Comment by GilbertLittle** [comment]
@uve - what happens in 2.2.4 is - you press play. The chart will draw to the first point. The tooltip doesn't show and you cannot click on this point. Press play again and chart will draw to the next point. Again, you cannot click on this new point, but you can now click on the previous point, and make it popup. In 2.2.3, you press play. The chart draws to the first point and the tooltip automatically shows. This continues for each remaining point. Thanks.

**Comment by uve** [comment]
@GilbertLittle, could you please record the video screencast that demonstrates the issue, and send it (with sample report) to  Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll check it.

**Comment by GilbertLittle** [comment]
@uve , I've sent an email with screencast and sample report to pbicvsupport@microsoft.com. Thanks.

**Comment by ignatvilesov** [comment]
Closed as obsolete.
